### ISSUE TITLE
Parameter "fd" is null

### ISSUE THREAD

**Issue by Zephilinox** [bitwes/Gut#749]
# Versions
*(list all versions where you have replicated the bug)*
* Godot: 4.4.1
* GUT: 9.5.0
* OS: Linux

# The Bug

Headless builds report

> update_scene_groups: end
reimport: begin: (Re)Importing Assets steps: 44
	reimport: step 0: Executing post-reimport operations...
ERROR: Parameter "fd" is null.
   at: _font_get_ascent (modules/text_server_adv/text_server_adv.cpp:2691)
ERROR: Parameter "fd" is null.
   at: _font_get_spacing (modules/text_server_adv/text_server_adv.cpp:2546)
ERROR: Parameter "fd" is null.
   at: _font_get_descent (modules/text_server_adv/text_server_adv.cpp:2725)
ERROR: Parameter "fd" is null.

# Steps To Reproduce

Build headlessly on a linux CI runner with `$GODOT_BIN --headless --editor --render-thread safe --single-threaded-scene --quit`

**Comment by Zephilinox** [comment]
<img width="662" height="117" alt="Image" src="https://github.com/user-attachments/assets/d06edc28-0e3c-4ca8-bddf-f48adfa89680" />

It's also in the editor, and is fixed by removing Gut from `Plugins`

**Comment by bitwes** [comment]
This appears to be a font issue.  

Please try this and see if it fixes it:
* Open the editor
* Bring up the GUT panel
* Show the text output panel if it isn't already (the "T" icon in top right)
* Click the "..." button in the text output panel.
* Change the font to "Default"
* Quit
* Run the headless editor command you posted.

<img width="1025" height="165" alt="Image" src="https://github.com/user-attachments/assets/9d3efa60-9225-40fd-bdfd-0bf9b80639cd" />

If you are including Editor Settings in your pipeline's build then this should resolve the issue (See the "Editor Settings" path at https://docs.godotengine.org/en/latest/tutorials/io/data_paths.html#editor-data-paths).  If not then you could probably short-circuit the font setting code by making `set_all_fonts` just `return`, until I get a fix in place.

https://github.com/bitwes/Gut/blob/bddf5169baad45e7476163b6c7560a50697fcb2c/addons/gut/gui/OutputText.gd#L313

GUT gets the font from Editor Settings.  The default font is CourierPrime, but the value "Default" is Godot's default font (which ends up being `null`, it's all confusing).

Dealing with fonts is the worst.  All I wanted was a fixed width font for my outputs because that's what we like.  Then I also wanted a font nobody would ever use because it looks dumb but was fun to include and that's why LobsterTwo was included.  Side note:  I once saw some admin editing bash scripts using Times New Roman.  I didn't trust his opinions anymore, nice guy though.

## Notes:
I tried to replicate the issue on my Mac with a little success.

## 
GUT:  `godot_4_5` branch
Godot: 4.5beta6
I got the error by switching the font in the bottom panel TextEdit control.  The number of errors printed scales with the amount of text that is in the text box.  It doesn't appear to error on startup, but any switching of the font, even back the original value which didn't error on startup, causes errors.

Switching while there was no text in the text box did not cause errors.  This is probably why it doesn't error on startup.

I was not able to replicate the issue using the provided command.

## 
GUT 9.50 (`main` branch)
Godot 4.4.1

I was not able to replicate the issue through the editor or using the provided command.

**Comment by Zephilinox** [comment]
this might be the best response I've ever had to an issue I've opened 😂 

>  making set_all_fonts just return

the modification to early return in that function did sort it in CI, though the fix with the font switch in-editor didn't fix it for me locally. we also aren't copying our EditorSettings over to CI (is that common :o). I've been... experimenting 😛 with all of this for a couple of hours now but I eventually realised the local errors were coming from a different addon we used 🤦 

In the end I removed every addon font, fixed up all the references to them including the scenes, and modified all of the functions that try to dynamically load or set fonts, and things are looking good now both on CI and locally. I noticed there was some dynamic font-related code commented out so I'm guessing this isn't the first time you've had to deal with these errors ☠️ 

I'm not quite sure what "version" of 9.5.0 we're using but it was grabbed roughly a month ago. I didn't realise at the time that it wasn't a proper release 🥹 

> Dealing with fonts is the worst. All I wanted was a fixed width font for my outputs because that's what we like. Then I also wanted a font nobody would ever use because it looks dumb but was fun to include and that's why LobsterTwo was included. Side note: I once saw some admin editing bash scripts using Times New Roman. I didn't trust his opinions anymore, nice guy though.

I loved the little story 😂 

> Side note: I once saw some admin editing bash scripts using Times New Roman

maybe freewill was a mistake 😥

thanks again for the super detailed response, it really helped me narrow things down to the fonts. it really sounds like the issue is on godots end more than anything. I really wish their C++ error messages had actual relevant information???

after your reply I also ended up watching your recent talk at GodotCon. You're an amazing speaker and I was really surprised to learn GUT was 10 years old

it's a great piece of software, thank you for working on it for so long, I look forward to seeing it around in 10 more years 😛

**Comment by bitwes** [comment]
Thank you! And you are welcome.


May I ask why you are including `--editor` in your command?  Are you testing a plugin that runs through the editor?


I'm going to keep this open until I can at least figure out what is going on with the `godot_4_5` branch.

**Comment by bitwes** [comment]
I think I narrowed down the cause of this, at least for the Godot 4.5 version of GUT.  I was able to replicate the issue outside of GUT.  I was able to stop it from happening by holding a reference to the loaded font.  Currently GUT loads the font, sets the font, then forgets about the font.

My theory is that the `TextEdit` control (or `Theme` or parent of `TextEdit`) is holding a weak reference to the current font.  When it attempts to change the font, the weak reference is no longer valid because it is ref-counted and nothing has a reference to it by then.  Your classic nullptr error.

**Comment by bitwes** [comment]
I hit "comment" too soon.  I just tried incorporating my POC into the actual OutputText scene and found that I was setting the font to "CourierNew" instead of "CourierPrime" when the control loaded.  I have no idea why this wouldn't have caused errors all the time, but it might be the cause of the error in the specific case this issue was opened for.

@Zephilinox if you want to try changing this line:
https://github.com/bitwes/Gut/blob/bddf5169baad45e7476163b6c7560a50697fcb2c/addons/gut/gui/OutputText.gd#L130C15-L130C25
to 
```gdscript
	var fname = 'CourierPrime'
```
(and remove the hacked `return` from `set_all_fonts`) it might fix the problem.

Also, FYI, in Godot 4.5(beta 6 currently) you DO get stack traces for C++ error messages!

**Comment by bitwes** [comment]
I created an issue for the 4.5 behavior (https://github.com/godotengine/godot/issues/110177#event-19461860359).  I had worked around the issue, but it has been fixed.  So, I think all of this will be squared away in the next release of Godot and GUT.  This will be closed out when the next version of GUT is released.
